apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hr-cloud-devops-service
  namespace: hr-cloud
  labels:
    app: hr-cloud-devops-service
spec:
  selector:
    matchLabels:
      app: hr-cloud-devops-service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
