apiVersion: v1
kind: Service
metadata:
  name: hr-cloud-devops-service
  namespace: hr-cloud
spec:
  type: ClusterIP
  selector:
    app: hr-cloud-devops-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
